# A cake recipe consist of a set of elements:
# a type of flour,
# sugar or another sweetener,
# some sort of fat,
# liquid (water or milk),
# a set of spices,
# a raising agent - baking powder for simplicity.
# There are also optional ingredients:
# fruits|vegetables|nuts|etc.

FLOUR = ['gluten-free flour',
         'spelt flour',
         'white flour',
         'wholegrain flour'].freeze

SUGAR = ['agave syrup',
         'black treacle',
         'brown sugar',
         'caster sugar',
         'golden syrup',
         'stevia',
         'vanilla sugar',
         'white sugar'].freeze

FAT = ['coconut milk',
       'coconut oil',
       'margarine',
       'olive oil',
       'rapeseed oil',
       'sunflower oil'].freeze

LIQUID = ['almond milk',
          'apple juice, non-filtered',
          'barley milk',
          'cashew milk',
          'hemp milk',
          'macadamia milk',
          'oat milk',
          'pear juice, non-filtered',
          'rice milk',
          'soy milk',
          'soy-rice milk',
          'spelt milk',
          'water'].freeze

SPICES = ['anise seed',
          'basil',
          'black pepper',
          'cardamon',
          'cayenne pepper',
          'chilli',
          'chopped parsley',
          'cinnamon',
          'cloves',
          'coriander powder',
          'cumin',
          'curry powder',
          'curry powder',
          'dill',
          'double espresso',
          'fresh coriander',
          'fresh ginger',
          'fresh mint',
          'garam masala',
          'marjoram leaves',
          'nutmeg',
          'orange peel',
          'powdered ginger',
          'rosemary',
          'thyme leaf',
          'vanilla extract'].freeze

OPTIONAL = [{ fruits: ['apricots',
                       'avocado',
                       'blueberries',
                       'cherries',
                       'chopped apples',
                       'chopped bananas',
                       'chopped mango',
                       'chopped nectarine',
                       'chopped pears',
                       'cooked pumpkin pulp',
                       'cooked sweet potato pulp',
                       'grated apples',
                       'plums',
                       'pomegranade seeds',
                       'raspberries',
                       'shredded beetroot',
                       'shredded carrots',
                       'shredded zucchini',
                       'smashed bananas',
                       'strawberries'] },
            { nuts: ['almond flakes',
                     'almond powder',
                     'chopped almonds',
                     'chopped cashews',
                     'chopped macadamia',
                     'chopped peanuts',
                     'chopped walnuts',
                     'dates',
                     'dried fruit mix',
                     'pecans',
                     'poppy seeds',
                     'raisins',
                     'walnut powder'] },
            { sprinkles: ['cacao',
                          'chopped chocolate',
                          'lemon zest',
                          'oats',
                          'shredded coconut'] },
            { other: ['a touch of love',
                      'hair of a unicorn',
                      'liberal guilt',
                      'rainbows',
                      'sparkles'] }].freeze
